// Auto-generated supply bills data from verified Excel sheet
const SUPPLY_BILLS_DATA = [
  {
    "invoice_date": "09-Nov-24",
    "invoice_date_iso": "2024-11-09",
    "time": "00:00",
    "source_pdf": "",
    "page": 1,
    "invoice_no": "",
    "sap_entry_no": "765570160",
    "tt_number": "",
    "material_code": "",
    "material_description": "",
    "product": "Diesel",
    "quantity_kl": 12.0,
    "unit": "KL",
    "material_total": 1062012.27,
    "invoice_total": 1062012.27,
    "doubt_or_discrepancy": ""
  },
  {
    "invoice_date": "10-Nov-24",
    "invoice_date_iso": "2024-11-10",
    "time": "00:00",
    "source_pdf": "",
    "page": 1,
    "invoice_no": "",
    "sap_entry_no": "785599560",
    "tt_number": "",
    "material_code": "",
    "material_description": "",
    "product": "Petrol",
    "quantity_kl": 8.0,
    "unit": "KL",
    "material_total": 813241.6,
    "invoice_total": 813244.6,
    "doubt_or_discrepancy": ""
  },
  {
    "invoice_date": "10-Nov-24",
    "invoice_date_iso": "2024-11-10",
    "time": "00:00",
    "source_pdf": "",
    "page": 1,
    "invoice_no": "",
    "sap_entry_no": "785599560",
    "tt_number": "",
    "material_code": "",
    "material_description": "",
    "product": "Petrol",
    "quantity_kl": 4.0,
    "unit": "KL",
    "material_total": 354004.09,
    "invoice_total": 0.0,
    "doubt_or_discrepancy": ""
  },
  {
    "invoice_date": "20-Nov-24",
    "invoice_date_iso": "2024-11-20",
    "time": "00:00",
    "source_pdf": "",
    "page": 1,
    "invoice_no": "",
    "sap_entry_no": "785911602",
    "tt_number": "",
    "material_code": "",
    "material_description": "",
    "product": "Diesel",
    "quantity_kl": 8.0,
    "unit": "KL",
    "material_total": 708008.18,
    "invoice_total": 1114628.98,
    "doubt_or_discrepancy": ""
  },
  {
    "invoice_date": "20-Nov-24",
    "invoice_date_iso": "2024-11-20",
    "time": "00:00",
    "source_pdf": "",
    "page": 1,
    "invoice_no": "",
    "sap_entry_no": "785911602",
    "tt_number": "",
    "material_code": "",
    "material_description": "",
    "product": "Petrol",
    "quantity_kl": 4.0,
    "unit": "KL",
    "material_total": 406620.8,
    "invoice_total": 1114628.98,
    "doubt_or_discrepancy": ""
  },
  {
    "invoice_date": "27-Nov-24",
    "invoice_date_iso": "2024-11-27",
    "time": "00:00",
    "source_pdf": "",
    "page": 1,
    "invoice_no": "",
    "sap_entry_no": "786240229",
    "tt_number": "",
    "material_code": "",
    "material_description": "",
    "product": "Petrol",
    "quantity_kl": 4.0,
    "unit": "KL",
    "material_total": 406620.8,
    "invoice_total": 0.0,
    "doubt_or_discrepancy": ""
  },
  {
    "invoice_date": "27-Nov-24",
    "invoice_date_iso": "2024-11-27",
    "time": "00:00",
    "source_pdf": "",
    "page": 1,
    "invoice_no": "",
    "sap_entry_no": "786240229",
    "tt_number": "",
    "material_code": "",
    "material_description": "",
    "product": "Diesel",
    "quantity_kl": 8.0,
    "unit": "KL",
    "material_total": 708008.18,
    "invoice_total": 1114628.98,
    "doubt_or_discrepancy": ""
  },
  {
    "invoice_date": "30-Nov-24",
    "invoice_date_iso": "2024-11-30",
    "time": "00:00",
    "source_pdf": "",
    "page": 1,
    "invoice_no": "",
    "sap_entry_no": "786368425",
    "tt_number": "",
    "material_code": "",
    "material_description": "",
    "product": "Diesel",
    "quantity_kl": 4.0,
    "unit": "KL",
    "material_total": 354004.09,
    "invoice_total": 0.0,
    "doubt_or_discrepancy": ""
  },
  {
    "invoice_date": "30-Nov-24",
    "invoice_date_iso": "2024-11-30",
    "time": "00:00",
    "source_pdf": "",
    "page": 1,
    "invoice_no": "",
    "sap_entry_no": "786368425",
    "tt_number": "",
    "material_code": "",
    "material_description": "",
    "product": "Petrol",
    "quantity_kl": 8.0,
    "unit": "KL",
    "material_total": 813211.6,
    "invoice_total": 1167215.69,
    "doubt_or_discrepancy": ""
  },
  {
    "invoice_date": "12-Dec-24",
    "invoice_date_iso": "2024-12-12",
    "time": "00:00",
    "source_pdf": "",
    "page": 1,
    "invoice_no": "",
    "sap_entry_no": "786768645",
    "tt_number": "",
    "material_code": "",
    "material_description": "",
    "product": "Diesel",
    "quantity_kl": 8.0,
    "unit": "KL",
    "material_total": 706967.53,
    "invoice_total": 0.0,
    "doubt_or_discrepancy": ""
  },
  {
    "invoice_date": "12-Dec-24",
    "invoice_date_iso": "2024-12-12",
    "time": "00:00",
    "source_pdf": "",
    "page": 1,
    "invoice_no": "",
    "sap_entry_no": "786768645",
    "tt_number": "",
    "material_code": "",
    "material_description": "",
    "product": "Petrol",
    "quantity_kl": 4.0,
    "unit": "KL",
    "material_total": 406020.67,
    "invoice_total": 1112988.0,
    "doubt_or_discrepancy": ""
  },
  {
    "invoice_date": "24-Dec-24",
    "invoice_date_iso": "2024-12-24",
    "time": "00:00",
    "source_pdf": "",
    "page": 1,
    "invoice_no": "",
    "sap_entry_no": "787140805",
    "tt_number": "",
    "material_code": "",
    "material_description": "",
    "product": "Diesel",
    "quantity_kl": 8.0,
    "unit": "KL",
    "material_total": 706967.53,
    "invoice_total": 0.0,
    "doubt_or_discrepancy": ""
  },
  {
    "invoice_date": "24-Dec-24",
    "invoice_date_iso": "2024-12-24",
    "time": "00:00",
    "source_pdf": "",
    "page": 1,
    "invoice_no": "",
    "sap_entry_no": "787140805",
    "tt_number": "",
    "material_code": "",
    "material_description": "",
    "product": "Petrol",
    "quantity_kl": 4.0,
    "unit": "KL",
    "material_total": 406020.67,
    "invoice_total": 1112988.2,
    "doubt_or_discrepancy": ""
  },
  {
    "invoice_date": "31-Dec-24",
    "invoice_date_iso": "2024-12-31",
    "time": "00:00",
    "source_pdf": "",
    "page": 1,
    "invoice_no": "",
    "sap_entry_no": "787457343",
    "tt_number": "",
    "material_code": "",
    "material_description": "",
    "product": "Diesel",
    "quantity_kl": 4.0,
    "unit": "KL",
    "material_total": 353483.76,
    "invoice_total": 0.0,
    "doubt_or_discrepancy": ""
  },
  {
    "invoice_date": "31-Dec-24",
    "invoice_date_iso": "2024-12-31",
    "time": "00:00",
    "source_pdf": "",
    "page": 1,
    "invoice_no": "",
    "sap_entry_no": "787457343",
    "tt_number": "",
    "material_code": "",
    "material_description": "",
    "product": "Petrol",
    "quantity_kl": 8.0,
    "unit": "KL",
    "material_total": 812041.33,
    "invoice_total": 1165525.09,
    "doubt_or_discrepancy": ""
  },
  {
    "invoice_date": "11-Jan-25",
    "invoice_date_iso": "2025-01-11",
    "time": "00:00",
    "source_pdf": "",
    "page": 1,
    "invoice_no": "",
    "sap_entry_no": "787886763",
    "tt_number": "",
    "material_code": "",
    "material_description": "",
    "product": "Diesel",
    "quantity_kl": 8.0,
    "unit": "KL",
    "material_total": 706967.53,
    "invoice_total": 0.0,
    "doubt_or_discrepancy": ""
  },
  {
    "invoice_date": "11-Jan-25",
    "invoice_date_iso": "2025-01-11",
    "time": "00:00",
    "source_pdf": "",
    "page": 1,
    "invoice_no": "",
    "sap_entry_no": "787886763",
    "tt_number": "",
    "material_code": "",
    "material_description": "",
    "product": "Petrol",
    "quantity_kl": 4.0,
    "unit": "KL",
    "material_total": 406020.67,
    "invoice_total": 1112988.0,
    "doubt_or_discrepancy": ""
  },
  {
    "invoice_date": "22-Jan-25",
    "invoice_date_iso": "2025-01-22",
    "time": "00:00",
    "source_pdf": "",
    "page": 1,
    "invoice_no": "",
    "sap_entry_no": "788221045",
    "tt_number": "",
    "material_code": "",
    "material_description": "",
    "product": "Diesel",
    "quantity_kl": 8.0,
    "unit": "KL",
    "material_total": 706967.53,
    "invoice_total": 0.0,
    "doubt_or_discrepancy": ""
  },
  {
    "invoice_date": "22-Jan-25",
    "invoice_date_iso": "2025-01-22",
    "time": "00:00",
    "source_pdf": "",
    "page": 1,
    "invoice_no": "",
    "sap_entry_no": "788221045",
    "tt_number": "",
    "material_code": "",
    "material_description": "",
    "product": "Petrol",
    "quantity_kl": 4.0,
    "unit": "KL",
    "material_total": 406020.67,
    "invoice_total": 1112988.2,
    "doubt_or_discrepancy": ""
  },
  {
    "invoice_date": "30-Jan-25",
    "invoice_date_iso": "2025-01-30",
    "time": "00:00",
    "source_pdf": "",
    "page": 1,
    "invoice_no": "",
    "sap_entry_no": "788538687",
    "tt_number": "",
    "material_code": "",
    "material_description": "",
    "product": "Diesel",
    "quantity_kl": 4.0,
    "unit": "KL",
    "material_total": 353483.76,
    "invoice_total": 0.0,
    "doubt_or_discrepancy": ""
  },
  {
    "invoice_date": "30-Jan-25",
    "invoice_date_iso": "2025-01-30",
    "time": "00:00",
    "source_pdf": "",
    "page": 1,
    "invoice_no": "",
    "sap_entry_no": "788538687",
    "tt_number": "",
    "material_code": "",
    "material_description": "",
    "product": "Petrol",
    "quantity_kl": 8.0,
    "unit": "KL",
    "material_total": 812041.33,
    "invoice_total": 1165525.09,
    "doubt_or_discrepancy": ""
  },
  {
    "invoice_date": "05-Feb-25",
    "invoice_date_iso": "2025-02-05",
    "time": "00:00",
    "source_pdf": "",
    "page": 1,
    "invoice_no": "",
    "sap_entry_no": "788804600",
    "tt_number": "",
    "material_code": "",
    "material_description": "",
    "product": "Diesel",
    "quantity_kl": 12.0,
    "unit": "KL",
    "material_total": 1060451.29,
    "invoice_total": 1060481.0,
    "doubt_or_discrepancy": ""
  },
  {
    "invoice_date": "15-Feb-25",
    "invoice_date_iso": "2025-02-15",
    "time": "00:00",
    "source_pdf": "",
    "page": 1,
    "invoice_no": "",
    "sap_entry_no": "789166995",
    "tt_number": "",
    "material_code": "",
    "material_description": "",
    "product": "Diesel",
    "quantity_kl": 8.0,
    "unit": "KL",
    "material_total": 706967.53,
    "invoice_total": 0.0,
    "doubt_or_discrepancy": ""
  },
  {
    "invoice_date": "15-Feb-25",
    "invoice_date_iso": "2025-02-15",
    "time": "00:00",
    "source_pdf": "",
    "page": 1,
    "invoice_no": "",
    "sap_entry_no": "789166995",
    "tt_number": "",
    "material_code": "",
    "material_description": "",
    "product": "Petrol",
    "quantity_kl": 4.0,
    "unit": "KL",
    "material_total": 406020.67,
    "invoice_total": 1112988.2,
    "doubt_or_discrepancy": ""
  },
  {
    "invoice_date": "21-Feb-25",
    "invoice_date_iso": "2025-02-21",
    "time": "00:00",
    "source_pdf": "",
    "page": 1,
    "invoice_no": "",
    "sap_entry_no": "789360743",
    "tt_number": "",
    "material_code": "",
    "material_description": "",
    "product": "Diesel",
    "quantity_kl": 4.0,
    "unit": "KL",
    "material_total": 353483.76,
    "invoice_total": 0.0,
    "doubt_or_discrepancy": ""
  },
  {
    "invoice_date": "21-Feb-25",
    "invoice_date_iso": "2025-02-21",
    "time": "00:00",
    "source_pdf": "",
    "page": 1,
    "invoice_no": "",
    "sap_entry_no": "789360743",
    "tt_number": "",
    "material_code": "",
    "material_description": "",
    "product": "Petrol",
    "quantity_kl": 8.0,
    "unit": "KL",
    "material_total": 812041.34,
    "invoice_total": 1165525.1,
    "doubt_or_discrepancy": ""
  },
  {
    "invoice_date": "28-Feb-25",
    "invoice_date_iso": "2025-02-28",
    "time": "00:00",
    "source_pdf": "",
    "page": 1,
    "invoice_no": "",
    "sap_entry_no": "789671722",
    "tt_number": "",
    "material_code": "",
    "material_description": "",
    "product": "Diesel",
    "quantity_kl": 4.0,
    "unit": "KL",
    "material_total": 353483.76,
    "invoice_total": 0.0,
    "doubt_or_discrepancy": ""
  },
  {
    "invoice_date": "28-Feb-25",
    "invoice_date_iso": "2025-02-28",
    "time": "00:00",
    "source_pdf": "",
    "page": 1,
    "invoice_no": "",
    "sap_entry_no": "789671722",
    "tt_number": "",
    "material_code": "",
    "material_description": "",
    "product": "Petrol",
    "quantity_kl": 8.0,
    "unit": "KL",
    "material_total": 812041.33,
    "invoice_total": 1165525.09,
    "doubt_or_discrepancy": ""
  },
  {
    "invoice_date": "08-Mar-25",
    "invoice_date_iso": "2025-03-08",
    "time": "00:00",
    "source_pdf": "",
    "page": 1,
    "invoice_no": "",
    "sap_entry_no": "760032385",
    "tt_number": "",
    "material_code": "",
    "material_description": "",
    "product": "Diesel",
    "quantity_kl": 12.0,
    "unit": "KL",
    "material_total": 1060451.29,
    "invoice_total": 1060451.29,
    "doubt_or_discrepancy": ""
  },
  {
    "invoice_date": "15-Mar-25",
    "invoice_date_iso": "2025-03-15",
    "time": "00:00",
    "source_pdf": "",
    "page": 1,
    "invoice_no": "",
    "sap_entry_no": "750285667",
    "tt_number": "",
    "material_code": "",
    "material_description": "",
    "product": "Diesel",
    "quantity_kl": 8.0,
    "unit": "KL",
    "material_total": 706967.53,
    "invoice_total": 0.0,
    "doubt_or_discrepancy": ""
  },
  {
    "invoice_date": "15-Mar-25",
    "invoice_date_iso": "2025-03-15",
    "time": "00:00",
    "source_pdf": "",
    "page": 1,
    "invoice_no": "",
    "sap_entry_no": "750285667",
    "tt_number": "",
    "material_code": "",
    "material_description": "",
    "product": "Petrol",
    "quantity_kl": 4.0,
    "unit": "KL",
    "material_total": 406020.67,
    "invoice_total": 1112988.2,
    "doubt_or_discrepancy": ""
  },
  {
    "invoice_date": "22-Mar-25",
    "invoice_date_iso": "2025-03-22",
    "time": "00:00",
    "source_pdf": "",
    "page": 1,
    "invoice_no": "",
    "sap_entry_no": "790474700",
    "tt_number": "",
    "material_code": "",
    "material_description": "",
    "product": "Diesel",
    "quantity_kl": 4.0,
    "unit": "KL",
    "material_total": 353480.76,
    "invoice_total": 0.0,
    "doubt_or_discrepancy": ""
  },
  {
    "invoice_date": "22-Mar-25",
    "invoice_date_iso": "2025-03-22",
    "time": "00:00",
    "source_pdf": "",
    "page": 1,
    "invoice_no": "",
    "sap_entry_no": "790474700",
    "tt_number": "",
    "material_code": "",
    "material_description": "",
    "product": "Petrol",
    "quantity_kl": 8.0,
    "unit": "KL",
    "material_total": 812041.34,
    "invoice_total": 1165522.1,
    "doubt_or_discrepancy": ""
  },
  {
    "invoice_date": "31-Mar-25",
    "invoice_date_iso": "2025-03-31",
    "time": "00:00",
    "source_pdf": "",
    "page": 1,
    "invoice_no": "",
    "sap_entry_no": "790837536",
    "tt_number": "",
    "material_code": "",
    "material_description": "",
    "product": "Diesel",
    "quantity_kl": 4.0,
    "unit": "KL",
    "material_total": 353480.76,
    "invoice_total": 0.0,
    "doubt_or_discrepancy": ""
  },
  {
    "invoice_date": "31-Mar-25",
    "invoice_date_iso": "2025-03-31",
    "time": "00:00",
    "source_pdf": "",
    "page": 1,
    "invoice_no": "",
    "sap_entry_no": "790837536",
    "tt_number": "",
    "material_code": "",
    "material_description": "",
    "product": "Petrol",
    "quantity_kl": 8.0,
    "unit": "KL",
    "material_total": 812041.34,
    "invoice_total": 1165522.1,
    "doubt_or_discrepancy": ""
  },
  {
    "invoice_date": "02-Apr-26",
    "invoice_date_iso": "2026-04-02",
    "time": "00:00",
    "source_pdf": "",
    "page": 1,
    "invoice_no": "",
    "sap_entry_no": "7005049068",
    "tt_number": "",
    "material_code": "",
    "material_description": "",
    "product": "Diesel",
    "quantity_kl": 8.0,
    "unit": "KL",
    "material_total": 706261.27,
    "invoice_total": 0.0,
    "doubt_or_discrepancy": ""
  },
  {
    "invoice_date": "02-Apr-26",
    "invoice_date_iso": "2026-04-02",
    "time": "00:00",
    "source_pdf": "",
    "page": 1,
    "invoice_no": "",
    "sap_entry_no": "7005049068",
    "tt_number": "",
    "material_code": "",
    "material_description": "",
    "product": "Petrol",
    "quantity_kl": 4.0,
    "unit": "KL",
    "material_total": 405615.05,
    "invoice_total": 1111876.32,
    "doubt_or_discrepancy": ""
  },
  {
    "invoice_date": "09-Apr-26",
    "invoice_date_iso": "2026-04-09",
    "time": "00:00",
    "source_pdf": "",
    "page": 1,
    "invoice_no": "",
    "sap_entry_no": "7005310319",
    "tt_number": "",
    "material_code": "",
    "material_description": "",
    "product": "Diesel",
    "quantity_kl": 8.0,
    "unit": "KL",
    "material_total": 706261.27,
    "invoice_total": 0.0,
    "doubt_or_discrepancy": ""
  },
  {
    "invoice_date": "09-Apr-26",
    "invoice_date_iso": "2026-04-09",
    "time": "00:00",
    "source_pdf": "",
    "page": 1,
    "invoice_no": "",
    "sap_entry_no": "7005310319",
    "tt_number": "",
    "material_code": "",
    "material_description": "",
    "product": "Petrol",
    "quantity_kl": 4.0,
    "unit": "KL",
    "material_total": 405615.05,
    "invoice_total": 1111876.32,
    "doubt_or_discrepancy": ""
  },
  {
    "invoice_date": "17-Apr-26",
    "invoice_date_iso": "2026-04-17",
    "time": "00:00",
    "source_pdf": "",
    "page": 1,
    "invoice_no": "",
    "sap_entry_no": "7005541411",
    "tt_number": "",
    "material_code": "",
    "material_description": "",
    "product": "Diesel",
    "quantity_kl": 8.0,
    "unit": "KL",
    "material_total": 706261.27,
    "invoice_total": 0.0,
    "doubt_or_discrepancy": ""
  },
  {
    "invoice_date": "17-Apr-26",
    "invoice_date_iso": "2026-04-17",
    "time": "00:00",
    "source_pdf": "",
    "page": 1,
    "invoice_no": "",
    "sap_entry_no": "7005541411",
    "tt_number": "",
    "material_code": "",
    "material_description": "",
    "product": "Petrol",
    "quantity_kl": 4.0,
    "unit": "KL",
    "material_total": 405615.05,
    "invoice_total": 1111876.32,
    "doubt_or_discrepancy": ""
  },
  {
    "invoice_date": "21-Apr-26",
    "invoice_date_iso": "2026-04-21",
    "time": "00:00",
    "source_pdf": "",
    "page": 1,
    "invoice_no": "",
    "sap_entry_no": "7005656963",
    "tt_number": "",
    "material_code": "",
    "material_description": "",
    "product": "Diesel",
    "quantity_kl": 4.0,
    "unit": "KL",
    "material_total": 353480.76,
    "invoice_total": 0.0,
    "doubt_or_discrepancy": ""
  },
  {
    "invoice_date": "21-Apr-26",
    "invoice_date_iso": "2026-04-21",
    "time": "00:00",
    "source_pdf": "",
    "page": 1,
    "invoice_no": "",
    "sap_entry_no": "7005656963",
    "tt_number": "",
    "material_code": "",
    "material_description": "",
    "product": "Petrol",
    "quantity_kl": 8.0,
    "unit": "KL",
    "material_total": 813202.44,
    "invoice_total": 1164361.0,
    "doubt_or_discrepancy": ""
  },
  {
    "invoice_date": "27-Apr-26",
    "invoice_date_iso": "2026-04-27",
    "time": "00:00",
    "source_pdf": "",
    "page": 1,
    "invoice_no": "",
    "sap_entry_no": "7005909337",
    "tt_number": "",
    "material_code": "",
    "material_description": "",
    "product": "Diesel",
    "quantity_kl": 8.0,
    "unit": "KL",
    "material_total": 706261.27,
    "invoice_total": 0.0,
    "doubt_or_discrepancy": ""
  },
  {
    "invoice_date": "27-Apr-26",
    "invoice_date_iso": "2026-04-27",
    "time": "00:00",
    "source_pdf": "",
    "page": 1,
    "invoice_no": "",
    "sap_entry_no": "7005909337",
    "tt_number": "",
    "material_code": "",
    "material_description": "",
    "product": "Petrol",
    "quantity_kl": 4.0,
    "unit": "KL",
    "material_total": 405615.05,
    "invoice_total": 1111876.32,
    "doubt_or_discrepancy": ""
  },
  {
    "invoice_date": "30-Apr-26",
    "invoice_date_iso": "2026-04-30",
    "time": "00:00",
    "source_pdf": "",
    "page": 1,
    "invoice_no": "",
    "sap_entry_no": "7006036618",
    "tt_number": "",
    "material_code": "",
    "material_description": "",
    "product": "Diesel",
    "quantity_kl": 8.0,
    "unit": "KL",
    "material_total": 706261.27,
    "invoice_total": 0.0,
    "doubt_or_discrepancy": ""
  },
  {
    "invoice_date": "30-Apr-26",
    "invoice_date_iso": "2026-04-30",
    "time": "00:00",
    "source_pdf": "",
    "page": 1,
    "invoice_no": "",
    "sap_entry_no": "7006036618",
    "tt_number": "",
    "material_code": "",
    "material_description": "",
    "product": "Petrol",
    "quantity_kl": 4.0,
    "unit": "KL",
    "material_total": 405615.05,
    "invoice_total": 1111876.32,
    "doubt_or_discrepancy": ""
  },
  {
    "invoice_date": "07-May-26",
    "invoice_date_iso": "2026-05-07",
    "time": "00:00",
    "source_pdf": "",
    "page": 1,
    "invoice_no": "",
    "sap_entry_no": "7006314126",
    "tt_number": "",
    "material_code": "",
    "material_description": "",
    "product": "Diesel",
    "quantity_kl": 8.0,
    "unit": "KL",
    "material_total": 706261.27,
    "invoice_total": 0.0,
    "doubt_or_discrepancy": ""
  },
  {
    "invoice_date": "07-May-26",
    "invoice_date_iso": "2026-05-07",
    "time": "00:00",
    "source_pdf": "",
    "page": 1,
    "invoice_no": "",
    "sap_entry_no": "7006314126",
    "tt_number": "",
    "material_code": "",
    "material_description": "",
    "product": "Petrol",
    "quantity_kl": 4.0,
    "unit": "KL",
    "material_total": 405615.05,
    "invoice_total": 1111876.32,
    "doubt_or_discrepancy": ""
  },
  {
    "invoice_date": "14-May-26",
    "invoice_date_iso": "2026-05-14",
    "time": "00:00",
    "source_pdf": "",
    "page": 1,
    "invoice_no": "",
    "sap_entry_no": "7006545471",
    "tt_number": "",
    "material_code": "",
    "material_description": "",
    "product": "Diesel",
    "quantity_kl": 8.0,
    "unit": "KL",
    "material_total": 706261.27,
    "invoice_total": 0.0,
    "doubt_or_discrepancy": ""
  },
  {
    "invoice_date": "14-May-26",
    "invoice_date_iso": "2026-05-14",
    "time": "00:00",
    "source_pdf": "",
    "page": 1,
    "invoice_no": "",
    "sap_entry_no": "7006545471",
    "tt_number": "",
    "material_code": "",
    "material_description": "",
    "product": "Petrol",
    "quantity_kl": 4.0,
    "unit": "KL",
    "material_total": 405615.05,
    "invoice_total": 1111876.32,
    "doubt_or_discrepancy": ""
  },
  {
    "invoice_date": "19-May-26",
    "invoice_date_iso": "2026-05-19",
    "time": "00:00",
    "source_pdf": "",
    "page": 1,
    "invoice_no": "",
    "sap_entry_no": "7006706997",
    "tt_number": "",
    "material_code": "",
    "material_description": "",
    "product": "Diesel",
    "quantity_kl": 4.0,
    "unit": "KL",
    "material_total": 368769.0,
    "invoice_total": 0.0,
    "doubt_or_discrepancy": ""
  },
  {
    "invoice_date": "19-May-26",
    "invoice_date_iso": "2026-05-19",
    "time": "00:00",
    "source_pdf": "",
    "page": 1,
    "invoice_no": "",
    "sap_entry_no": "7006706997",
    "tt_number": "",
    "material_code": "",
    "material_description": "",
    "product": "Petrol",
    "quantity_kl": 8.0,
    "unit": "KL",
    "material_total": 844460.94,
    "invoice_total": 1213229.94,
    "doubt_or_discrepancy": ""
  },
  {
    "invoice_date": "21-May-26",
    "invoice_date_iso": "2026-05-21",
    "time": "00:00",
    "source_pdf": "",
    "page": 1,
    "invoice_no": "",
    "sap_entry_no": "7006785146",
    "tt_number": "",
    "material_code": "",
    "material_description": "",
    "product": "Diesel",
    "quantity_kl": 12.0,
    "unit": "KL",
    "material_total": 1106307.01,
    "invoice_total": 1106307.01,
    "doubt_or_discrepancy": ""
  },
  {
    "invoice_date": "23-May-26",
    "invoice_date_iso": "2026-05-23",
    "time": "00:00",
    "source_pdf": "",
    "page": 1,
    "invoice_no": "",
    "sap_entry_no": "7006835858",
    "tt_number": "",
    "material_code": "",
    "material_description": "",
    "product": "Diesel",
    "quantity_kl": 12.0,
    "unit": "KL",
    "material_total": 11117318.0,
    "invoice_total": 11117318.0,
    "doubt_or_discrepancy": ""
  },
  {
    "invoice_date": "26-May-26",
    "invoice_date_iso": "2026-05-26",
    "time": "00:00",
    "source_pdf": "",
    "page": 1,
    "invoice_no": "",
    "sap_entry_no": "7007001039",
    "tt_number": "",
    "material_code": "",
    "material_description": "",
    "product": "Diesel",
    "quantity_kl": 12.0,
    "unit": "KL",
    "material_total": 1149871.16,
    "invoice_total": 1149871.16,
    "doubt_or_discrepancy": ""
  },
  {
    "invoice_date": "29-May-26",
    "invoice_date_iso": "2026-05-29",
    "time": "00:00",
    "source_pdf": "",
    "page": 1,
    "invoice_no": "",
    "sap_entry_no": "7007103283",
    "tt_number": "",
    "material_code": "",
    "material_description": "",
    "product": "Diesel",
    "quantity_kl": 8.0,
    "unit": "KL",
    "material_total": 766580.77,
    "invoice_total": 0.0,
    "doubt_or_discrepancy": ""
  },
  {
    "invoice_date": "29-May-26",
    "invoice_date_iso": "2026-05-29",
    "time": "00:00",
    "source_pdf": "",
    "page": 1,
    "invoice_no": "",
    "sap_entry_no": "7007103283",
    "tt_number": "",
    "material_code": "",
    "material_description": "",
    "product": "Petrol",
    "quantity_kl": 4.0,
    "unit": "KL",
    "material_total": 437101.09,
    "invoice_total": 1203681.86,
    "doubt_or_discrepancy": ""
  },
  {
    "invoice_date": "02-Jun-26",
    "invoice_date_iso": "2026-06-02",
    "time": "00:00",
    "source_pdf": "",
    "page": 1,
    "invoice_no": "",
    "sap_entry_no": "7007239664",
    "tt_number": "",
    "material_code": "",
    "material_description": "",
    "product": "Diesel",
    "quantity_kl": 12.0,
    "unit": "KL",
    "material_total": 1149871.16,
    "invoice_total": 1149871.0,
    "doubt_or_discrepancy": ""
  },
  {
    "invoice_date": "05-Jun-26",
    "invoice_date_iso": "2026-06-05",
    "time": "00:00",
    "source_pdf": "",
    "page": 1,
    "invoice_no": "",
    "sap_entry_no": "7007392887",
    "tt_number": "",
    "material_code": "",
    "material_description": "",
    "product": "Petrol",
    "quantity_kl": 12.0,
    "unit": "KL",
    "material_total": 1311303.27,
    "invoice_total": 1311303.0,
    "doubt_or_discrepancy": ""
  },
  {
    "invoice_date": "11-Jun-26",
    "invoice_date_iso": "2026-06-11",
    "time": "00:00",
    "source_pdf": "",
    "page": 1,
    "invoice_no": "",
    "sap_entry_no": "7007583709",
    "tt_number": "",
    "material_code": "",
    "material_description": "",
    "product": "Diesel",
    "quantity_kl": 12.0,
    "unit": "KL",
    "material_total": 1149871.16,
    "invoice_total": 1149871.16,
    "doubt_or_discrepancy": ""
  },
  {
    "invoice_date": "18-Jun-26",
    "invoice_date_iso": "2026-06-18",
    "time": "00:00",
    "source_pdf": "",
    "page": 1,
    "invoice_no": "",
    "sap_entry_no": "7007801535",
    "tt_number": "",
    "material_code": "",
    "material_description": "",
    "product": "Diesel",
    "quantity_kl": 8.0,
    "unit": "KL",
    "material_total": 766580.77,
    "invoice_total": 0.0,
    "doubt_or_discrepancy": ""
  },
  {
    "invoice_date": "18-Jun-26",
    "invoice_date_iso": "2026-06-18",
    "time": "00:00",
    "source_pdf": "",
    "page": 1,
    "invoice_no": "",
    "sap_entry_no": "7007801535",
    "tt_number": "",
    "material_code": "",
    "material_description": "",
    "product": "Petrol",
    "quantity_kl": 4.0,
    "unit": "KL",
    "material_total": 437101.09,
    "invoice_total": 1203681.86,
    "doubt_or_discrepancy": ""
  },
  {
    "invoice_date": "24-Jun-26",
    "invoice_date_iso": "2026-06-24",
    "time": "00:00",
    "source_pdf": "",
    "page": 1,
    "invoice_no": "",
    "sap_entry_no": "7007988900",
    "tt_number": "",
    "material_code": "",
    "material_description": "",
    "product": "Diesel",
    "quantity_kl": 8.0,
    "unit": "KL",
    "material_total": 766580.9099999999,
    "invoice_total": 1203682.0,
    "doubt_or_discrepancy": ""
  }
];
